title: Zach's site
email: zmmille2@gmail.com
name: Zach Miller, Software Dev
github_username: zmmille2

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /blog/:year/:month/:day/:title
